### ISSUE TITLE
Mailcatcher error during site install

### ISSUE THREAD

**Issue by wwhurley** [forumone/web-starter#105]
/home/vagrant/.rbenv/versions/1.9.3-p484/lib/ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find mailcatcher (>= 0) amongst [bigdecimal-1.1.0, breakpoint-2.5.0, bundler-1.10.5, capistrano-3.4.0, chunky_png-1.3.4, colorize-0.7.7, compass-1.0.3, compass-core-1.0.3, compass-import-once-1.0.5, ffi-1.9.10, i18n-0.7.0, io-console-0.3, json-1.5.5, minitest-2.5.1, multi_json-1.11.2, net-scp-1.2.1, net-ssh-2.9.2, rake-10.4.2, rake-0.9.2.2, rb-fsevent-0.9.5, rb-inotify-0.9.5, rdoc-3.9.5, sass-3.4.16, sass-globbing-1.1.0, sassy-maps-0.4.0, singularitygs-1.6.2, sshkit-1.7.1](Gem::LoadError)

from /home/vagrant/.rbenv/versions/1.9.3-p484/lib/ruby/1.9.1/rubygems/dependency.rb:256:in `to_spec'

from /home/vagrant/.rbenv/versions/1.9.3-p484/lib/ruby/1.9.1/rubygems.rb:1231:in `gem'

from /usr/bin/catchmail:18:in `<main>'

I'm getting this via the CLI when running drush si {profile name}

**Comment by wwhurley** [comment]
Due to ownership of the PHP process and rbenv the version of ruby was different between what was running mailcatcher as a service and how it was invoked in response to the mail() function. Adding it to the project should resolve that.
